spring.application.name=demo

# OAuth2 Authorization Server Client Configuration
spring.security.oauth2.authorizationserver.client.my-client.registration.client-id=my-client
spring.security.oauth2.authorizationserver.client.my-client.registration.client-secret={noop}my-secret
spring.security.oauth2.authorizationserver.client.my-client.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.my-client.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.my-client.registration.scopes=read,write
